# Podstawowa obsługa sprzętu (GPIO, PWM, I2C, Enkodery/Sensory)
CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_SENSOR=y
CONFIG_I2C=y

# Obsługa UART i bufora dla micro-ROS (KRYTYCZNE: obsługa przerwana UART)
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_RING_BUFFER=y

# Pamięć sterty (KRYTYCZNE: micro-ROS wymaga alokacji dynamicznej dla DDS)
CONFIG_HEAP_MEM_POOL_SIZE=16384

# Wymagana obsługa POSIX dla micro-ROS
CONFIG_POSIX_API=y
CONFIG_POSIX_CLOCK=y
CONFIG_PTHREAD_IPC=y

# Wymagana obsługa konstruktorów GNU przez bibliotekę micro-ROS
CONFIG_STATIC_INIT_GNU=y

# Moduł micro-ROS
CONFIG_MICROROS=y

# Formatowanie zmiennoprzecinkowych (float) w Libc
CONFIG_NEWLIB_LIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Wyłączenie konsoli Zephyra (aby nie zakłócać transmisji szeregowej micro-ROS)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_BOOT_BANNER=n
CONFIG_PRINTK=y

# Stos i pamięć wątków
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096