CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_SENSOR=y
CONFIG_PRINTK=y
CONFIG_QDEC_STM32=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_I2C=y
CONFIG_MICROROS=y
CONFIG_POSIX_SYSCONF_IMPL_FULL=y
CONFIG_POSIX_SYSCONF=n
CONFIG_POSIX_API=y
CONFIG_POSIX_CLOCK=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y
CONFIG_STATIC_INIT_GNU=y

CONFIG_BOOT_BANNER=n